debug: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database: mysql
        show-sql: true
      properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: true
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infopublic?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: Root1234